/* Mini Database */
// Generate image paths

export const PRODUCTS = [
    // FILE 1: LAPTOP SKINS (Pages 1-11)
    { id: "ls1", category: "Laptop Skins", name: "Catholic Collage", basePrice: 249, image: "/Laptop/1.jpg", description: "Minimalist Jesus typography design.", hasVariants: false },
    { id: "ls2", category: "Laptop Skins", name: "Thy Will Be Done", basePrice: 249, image: "/Laptop/2.jpg", description: "Luke 22:42 inspired prayer design.", hasVariants: false },
    { id: "ls3", category: "Laptop Skins", name: "First Loved", basePrice: 249, image: "/Laptop/3.jpg", description: "1 John 4:19 - We love because He first loved us.", hasVariants: false },
    { id: "ls4", category: "Laptop Skins", name: "The Boss", basePrice: 249, image: "/Laptop/4.jpg", description: "Leadership / God is in charge design.", hasVariants: false },
    { id: "ls5", category: "Laptop Skins", name: "Fishers of Men", basePrice: 249, image: "/Laptop/5.jpg", description: "Evangelical theme inspired by the Gospels.", hasVariants: false },
    { id: "ls6", category: "Laptop Skins", name: "Be Strong & Courageous", basePrice: 249, image: "/Laptop/6.jpg", description: "Joshua 1:9 verse design: Do not be afraid.", hasVariants: false },
    { id: "ls7", category: "Laptop Skins", name: "Original Love Letters", basePrice: 249, image: "/Laptop/7.jpg", description: "Bible design with 'OXOX' motif.", hasVariants: false },
    /*
    { id: "ls8", category: "Laptop Skins", name: "Fight My Battles", basePrice: 249, image: "/Laptop/8.jpg", description: "This is how I fight my battles.", hasVariants: false },
    { id: "ls9", category: "Laptop Skins", name: "Daughter of the King", basePrice: 249, image: "/Laptop/9.jpg", description: "Royal identity affirmation.", hasVariants: false },
    { id: "ls10", category: "Laptop Skins", name: "Reckless Love", basePrice: 249, image: "/Laptop/10.jpg", description: "Overwhelming, never-ending, reckless love of God.", hasVariants: false },
    { id: "ls11", category: "Laptop Skins", name: "Adonai Elohim", basePrice: 249, image: "/Laptop/11.jpg", description: "Hebrew names of God design.", hasVariants: false },
    { id: "ls12", category: "Laptop Skins", name: "Rejoice Always", basePrice: 249, image: "/Laptop/12.jpg", description: "1 Thessalonians 5:16-18 reminder to pray continually.", hasVariants: false },
    { id: "ls13", category: "Laptop Skins", name: "Your Will Be Done", basePrice: 249, image: "/Laptop/13.jpg", description: "Luke 22:42 prayer design (Page 2 variant).", hasVariants: false },
    { id: "ls14", category: "Laptop Skins", name: "Think Positively List", basePrice: 249, image: "/Laptop/14.jpg", description: "Checklist: Network Well, Exercise Daily, Eat Healthy, etc.", hasVariants: false },
    */

    // STICKERS
    { id: "st1", category: "Stickers", name: "Forgiven", basePrice: 25, image: "/Stickers/1.jpg", description: "Assurance of salvation.", hasVariants: false },
    { id: "st2", category: "Stickers", name: "Te Amo", basePrice: 25, image: "/Stickers/2.jpg", description: "Spanish for 'I Love You'.", hasVariants: false },
    { id: "st3", category: "Stickers", name: "You Are Loved", basePrice: 25, image: "/Stickers/3.jpg", description: "Simple affirmation design.", hasVariants: false },
    { id: "st4", category: "Stickers", name: "Coffee", basePrice: 25, image: "/Stickers/4.jpg", description: "For the coffee lovers.", hasVariants: false },
    { id: "st5", category: "Stickers", name: "Be The Light", basePrice: 25, image: "/Stickers/5.jpg", description: "Matthew 5:14 inspired.", hasVariants: false },
    { id: "st6", category: "Stickers", name: "Faith (Minimal)", basePrice: 25, image: "/Stickers/6.jpg", description: "Minimalist Faith typography.", hasVariants: false },
    { id: "st7", category: "Stickers", name: "Believe", basePrice: 25, image: "/Stickers/7.jpg", description: "Simple Believe typography.", hasVariants: false },
    { id: "st8", category: "Stickers", name: "Daughter of the King", basePrice: 25, image: "/Stickers/8.jpg", description: "Royal identity affirmation.", hasVariants: false },
    { id: "st9", category: "Stickers", name: "Blessed", basePrice: 25, image: "/Stickers/9.jpg", description: "Simple Blessed typography.", hasVariants: false },
    { id: "st10", category: "Stickers", name: "Pray More Worry Less", basePrice: 25, image: "/Stickers/10.jpg", description: "Reminder to turn anxiety into prayer.", hasVariants: false },
    { id: "st11", category: "Stickers", name: "Saved By Grace", basePrice: 25, image: "/Stickers/11.jpg", description: "Ephesians 2:8 inspired design.", hasVariants: false },
    { id: "st12", category: "Stickers", name: "Hope", basePrice: 25, image: "/Stickers/12.jpg", description: "Minimalist Hope typography.", hasVariants: false },
    { id: "st13", category: "Stickers", name: "Love", basePrice: 25, image: "/Stickers/13.jpg", description: "Minimalist Love typography.", hasVariants: false },
    { id: "st14", category: "Stickers", name: "Jesus Loves You", basePrice: 25, image: "/Stickers/14.jpg", description: "Evangelistic message.", hasVariants: false },
    { id: "st15", category: "Stickers", name: "YHWH", basePrice: 25, image: "/Stickers/15.jpg", description: "The Tetragrammaton / Name of God.", hasVariants: false },
    { id: "st16", category: "Stickers", name: "Fight My Battles", basePrice: 25, image: "/Stickers/16.jpg", description: "This is how I fight my battles.", hasVariants: false },
    { id: "st17", category: "Stickers", name: "Kind Words / Honey", basePrice: 25, image: "/Stickers/17.jpg", description: "Kind words are like honey sweet to the soul.", hasVariants: false },
    { id: "st18", category: "Stickers", name: "Psalm 91:4", basePrice: 25, image: "/Stickers/18.jpg", description: "He will cover you with his feathers.", hasVariants: false },
    { id: "st19", category: "Stickers", name: "Spread Kindness", basePrice: 25, image: "/Stickers/19.jpg", description: "Inspirational kindness sticker.", hasVariants: false },


    // --- Page 13 Items ---
    { id: "st20", category: "Stickers", name: "Dream Big Stay Humble", basePrice: 25, image: "/Stickers/20.jpg", description: "Balanced life advice sticker.", hasVariants: false },
    { id: "st21", category: "Stickers", name: "Dare to Dream", basePrice: 25, image: "/Stickers/21.jpg", description: "Motivational sticker for dreamers.", hasVariants: false },
    { id: "st22", category: "Stickers", name: "Rejoice Always", basePrice: 25, image: "/Stickers/22.jpg", description: "1 Thessalonians 5:16.", hasVariants: false },
    { id: "st23", category: "Stickers", name: "Hello Child of God", basePrice: 25, image: "/Stickers/23.jpg", description: "Identity name tag sticker.", hasVariants: false },
    { id: "st24", category: "Stickers", name: "I'd Rather Have Jesus", basePrice: 25, image: "/Stickers/24.jpg", description: "Statement of priority and devotion.", hasVariants: false },
    { id: "st25", category: "Stickers", name: "Agape", basePrice: 25, image: "/Stickers/25.jpg", description: "Greek word for unconditional love.", hasVariants: false },
    { id: "st26", category: "Stickers", name: "You Are Chosen", basePrice: 25, image: "/Stickers/26.jpg", description: "Identity sticker.", hasVariants: false },
    //{ id: "st27", category: "Stickers", name: "You Are Worthy", basePrice: 25, image: "/Stickers/27.jpg", description: "Self-worth affirmation.", hasVariants: false },
    { id: "st28", category: "Stickers", name: "Count Blessings", basePrice: 25, image: "/Stickers/28.jpg", description: "Gratitude reminder.", hasVariants: false },
    { id: "st29", category: "Stickers", name: "Overwhelming Love", basePrice: 25, image: "/Stickers/29.jpg", description: "Reckless love of God.", hasVariants: false },
    { id: "st30", category: "Stickers", name: "Thy Will Be Done", basePrice: 25, image: "/Stickers/30.jpg", description: "Prayer sticker.", hasVariants: false },
    { id: "st31", category: "Stickers", name: "Original Love Letters", basePrice: 25, image: "/Stickers/31.jpg", description: "Bible with OXOX motif.", hasVariants: false },
    { id: "st32", category: "Stickers", name: "Faith Typography", basePrice: 25, image: "/Stickers/32.jpg", description: "Creative Faith text design.", hasVariants: false },
    { id: "st33", category: "Stickers", name: "Butterfly", basePrice: 25, image: "/Stickers/33.jpg", description: "Colorful butterfly sticker.", hasVariants: false },
    { id: "st34", category: "Stickers", name: "Honey Pot", basePrice: 25, image: "/Stickers/34.jpg", description: "Cute honey pot illustration.", hasVariants: false },
    { id: "st35", category: "Stickers", name: "YHWH Typography", basePrice: 25, image: "/Stickers/35.jpg", description: "Stylized Name of God.", hasVariants: false },
    { id: "st36", category: "Stickers", name: "Jesus Super Hero", basePrice: 25, image: "/Stickers/36.jpg", description: "Jesus standing with superheroes.", hasVariants: false },
    { id: "st37", category: "Stickers", name: "Good Shepherd Cute", basePrice: 25, image: "/Stickers/37.jpg", description: "Kawaii style Jesus with sheep.", hasVariants: false },
    { id: "st38", category: "Stickers", name: "Blessed Script", basePrice: 25, image: "/Stickers/38.jpg", description: "Script font Blessed sticker.", hasVariants: false },

    /* --- PREVIOUS ITEMS (Shifted down: Old st32 became st39, etc.) ---
    { id: "st39", category: "Stickers", name: "Jesus Heals", basePrice: 25, image: "/Stickers/39.jpg", description: "Simple and powerful healing declaration.", hasVariants: false },
    { id: "st40", category: "Stickers", name: "Faith (Script)", basePrice: 25, image: "/Stickers/40.jpg", description: "Script typography Faith.", hasVariants: false },
    { id: "st41", category: "Stickers", name: "Holy Bible", basePrice: 25, image: "/Stickers/41.jpg", description: "Iconic Bible design.", hasVariants: false },
    { id: "st42", category: "Stickers", name: "Spirit Lead Me", basePrice: 25, image: "/Stickers/42.jpg", description: "Prayer for guidance.", hasVariants: false },
    { id: "st43", category: "Stickers", name: "Love Never Fails", basePrice: 25, image: "/Stickers/43.jpg", description: "1 Corinthians 13.", hasVariants: false },
    { id: "st44", category: "Stickers", name: "Faith Over Fear", basePrice: 25, image: "/Stickers/44.jpg", description: "Bold faith statement.", hasVariants: false },
    { id: "st45", category: "Stickers", name: "Be Still", basePrice: 25, image: "/Stickers/45.jpg", description: "Be still and know that I am God.", hasVariants: false },
    { id: "st46", category: "Stickers", name: "Jesus Is King", basePrice: 25, image: "/Stickers/46.jpg", description: "Bold declaration of kingship.", hasVariants: false },
    { id: "st47", category: "Stickers", name: "Love God Love People", basePrice: 25, image: "/Stickers/47.jpg", description: "The greatest commandments.", hasVariants: false },
    { id: "st48", category: "Stickers", name: "Set Your Mind", basePrice: 25, image: "/Stickers/48.jpg", description: "Set your mind on things above.", hasVariants: false },
    { id: "st49", category: "Stickers", name: "His Love Knows No Limits", basePrice: 25, image: "/Stickers/49.jpg", description: "Limitless love design.", hasVariants: false },
    { id: "st50", category: "Stickers", name: "Trust In The Lord", basePrice: 25, image: "/Stickers/50.jpg", description: "Proverbs 3:5.", hasVariants: false },
    { id: "st51", category: "Stickers", name: "She Is Worthy", basePrice: 25, image: "/Stickers/51.jpg", description: "Proverbs 31.", hasVariants: false },
    { id: "st52", category: "Stickers", name: "Faith Can Move Mountains", basePrice: 25, image: "/Stickers/52.jpg", description: "Mountain moving faith.", hasVariants: false },
    { id: "st53", category: "Stickers", name: "Psalm 23", basePrice: 25, image: "/Stickers/53.jpg", description: "The Lord is my shepherd.", hasVariants: false },
    { id: "st54", category: "Stickers", name: "Light of the World", basePrice: 25, image: "/Stickers/54.jpg", description: "You are the light of the world.", hasVariants: false },
    { id: "st55", category: "Stickers", name: "Woman of God", basePrice: 25, image: "/Stickers/55.jpg", description: "Identity affirmation.", hasVariants: false },
    { id: "st56", category: "Stickers", name: "He Has A Plan", basePrice: 25, image: "/Stickers/56.jpg", description: "He has a plan and I have a purpose.", hasVariants: false },
    */

        // FILE 1: BADGES (Page 15) 
    { id: "bd1", category: "Badges", name: "Daughter of the King Badge", basePrice: 79, image: "/Badges/1.jpg", description: "Royal identity badge.", hasVariants: false },
    { id: "bd2", category: "Badges", name: "Psalm 91:4 Badge", basePrice: 79, image: "/Badges/2.jpg", description: "Feathers protection badge.", hasVariants: false },
    //{ id: "bd3", category: "Badges", name: "Jesus Loves You Badge", basePrice: 79, image: "/Badges/3.jpg", description: "Message of love badge.", hasVariants: false },
    { id: "bd4", category: "Badges", name: "You Are Loved Badge", basePrice: 79, image: "/Badges/4.jpg", description: "Affirmation badge.", hasVariants: false },
    { id: "bd5", category: "Badges", name: "Faith Badge", basePrice: 79, image: "/Badges/5.jpg", description: "Faith badge.", hasVariants: false },
    { id: "bd6", category: "Badges", name: "Coffee Badge", basePrice: 79, image: "/Badges/6.jpg", description: "Coffee lover badge.", hasVariants: false },
    { id: "bd7", category: "Badges", name: "She Is Worthy Badge", basePrice: 79, image: "/Badges/7.jpg", description: "Proverbs 31 badge.", hasVariants: false },
    { id: "bd8", category: "Badges", name: "Fight My Battles Badge", basePrice: 79, image: "/Badges/8.jpg", description: "Worship song badge.", hasVariants: false },
    { id: "bd9", category: "Badges", name: "Plan and Purpose Badge", basePrice: 79, image: "/Badges/9.jpg", description: "He has a plan badge.", hasVariants: false },
    { id: "bd10", category: "Badges", name: "Love Badge", basePrice: 79, image: "/Badges/10.jpg", description: "Love badge.", hasVariants: false },
    { id: "bd11", category: "Badges", name: "Faith Over Fear Badge", basePrice: 79, image: "/Badges/11.jpg", description: "Faith over fear badge.", hasVariants: false },
    { id: "bd12", category: "Badges", name: "Love Never Fails Badge", basePrice: 79, image: "/Badges/12.jpg", description: "Love never fails badge.", hasVariants: false },
    { id: "bd13", category: "Badges", name: "Forever Kinda Love Badge", basePrice: 79, image: "/Badges/13.jpg", description: "Matt 28:20 badge.", hasVariants: false },
    { id: "bd14", category: "Badges", name: "Holy Bible Badge", basePrice: 79, image: "/Badges/14.jpg", description: "Bible icon badge.", hasVariants: false },
    { id: "bd15", category: "Badges", name: "Set Your Mind Badge", basePrice: 79, image: "/Badges/15.jpg", description: "Colossians 3:2 badge.", hasVariants: false },
    { id: "bd16", category: "Badges", name: "Butterfly Badge", basePrice: 79, image: "/Badges/16.jpg", description: "Butterfly illustration.", hasVariants: false },
    { id: "bd17", category: "Badges", name: "Floral Cross Badge", basePrice: 79, image: "/Badges/17.jpg", description: "Cross with flowers.", hasVariants: false },
    { id: "bd18", category: "Badges", name: "Cross & Heart Badge", basePrice: 79, image: "/Badges/18.jpg", description: "Symbol of faith and love.", hasVariants: false },
    { id: "bd19", category: "Badges", name: "Jesus Hug Badge", basePrice: 79, image: "/Badges/19.jpg", description: "Jesus hugging a girl illustration.", hasVariants: false },
    { id: "bd20", category: "Badges", name: "Cute Shepherd Badge", basePrice: 79, image: "/Badges/20.jpg", description: "Cute Jesus with sheep.", hasVariants: false },
    { id: "bd21", category: "Badges", name: "Mary Full Length", basePrice: 79, image: "/Badges/21.jpg", description: "Full portrait of Mother Mary.", hasVariants: false },
    { id: "bd22", category: "Badges", name: "Mary Portrait", basePrice: 79, image: "/Badges/22.jpg", description: "Close-up portrait of Mother Mary.", hasVariants: false },
    { id: "bd23", category: "Badges", name: "Coffee Cat Badge", basePrice: 79, image: "/Badges/23.jpg", description: "Whimsical coffee and cat design.", hasVariants: false },
    { id: "bd24", category: "Badges", name: "Jesus Minimal Art", basePrice: 79, image: "/Badges/24.jpg", description: "Minimalist art of Jesus.", hasVariants: false },
    { id: "bd25", category: "Badges", name: "Good Shepherd Badge", basePrice: 79, image: "/Badges/25.jpg", description: "Jesus holding a lamb.", hasVariants: false },

    // FILE 2: BOOKMARKS (Pages 1-4)
    { id: "bm1", category: "Bookmarks", name: "God is Love", basePrice: 25, image: "/Bookmarks/1.jpg", description: "Bold typographic statement.", hasVariants: false },
    { id: "bm2", category: "Bookmarks", name: "Plans to Prosper", basePrice: 25, image: "/Bookmarks/2.jpg", description: "Jeremiah 29:11 - Hope and a future.", hasVariants: false },
    { id: "bm3", category: "Bookmarks", name: "Faith Definition", basePrice: 25, image: "/Bookmarks/3.jpg", description: "Hebrews 11:1 - Assurance of things hoped for.", hasVariants: false },
    { id: "bm4", category: "Bookmarks", name: "First Loved", basePrice: 25, image: "/Bookmarks/4.jpg", description: "1 John 4:19 - We love because He first loved us.", hasVariants: false },
    { id: "bm5", category: "Bookmarks", name: "Be Still", basePrice: 25, image: "/Bookmarks/5.jpg", description: "Be Still and know that I am GOD.", hasVariants: false },
    { id: "bm6", category: "Bookmarks", name: "Let Your Light Shine", basePrice: 25, image: "/Bookmarks/6.jpg", description: "Inspirational light bulb or sun motif.", hasVariants: false },
    { id: "bm7", category: "Bookmarks", name: "Restless Hearts", basePrice: 25, image: "/Bookmarks/7.jpg", description: "Our hearts are restless until they rest in you.", hasVariants: false },
    { id: "bm8", category: "Bookmarks", name: "Dream", basePrice: 25, image: "/Bookmarks/8.jpg", description: "Simple dream typography.", hasVariants: false },
    { id: "bm9", category: "Bookmarks", name: "As The Deer", basePrice: 25, image: "/Bookmarks/9.jpg", description: "Psalm 42:1 - Spiritual thirst and longing.", hasVariants: false },
    { id: "bm10", category: "Bookmarks", name: "God So Loved", basePrice: 25, image: "/Bookmarks/10.jpg", description: "John 3:16 - The Gospel message.", hasVariants: false },
    { id: "bm11", category: "Bookmarks", name: "New Creation", basePrice: 25, image: "/Bookmarks/11.jpg", description: "2 Corinthians 5:17 - The old has gone, the new is here.", hasVariants: false },
    { id: "bm12", category: "Bookmarks", name: "Faith Moves Mountains", basePrice: 25, image: "/Bookmarks/12.jpg", description: "Motivational faith design.", hasVariants: false },
    { id: "bm13", category: "Bookmarks", name: "Renew Strength", basePrice: 25, image: "/Bookmarks/13.jpg", description: "Isaiah 40:31 - Eagle imagery.", hasVariants: false },
    { id: "bm14", category: "Bookmarks", name: "Lord With You", basePrice: 25, image: "/Bookmarks/14.jpg", description: "The Lord is with you wherever you go.", hasVariants: false },
    { id: "bm15", category: "Bookmarks", name: "Bloom Where Planted", basePrice: 25, image: "/Bookmarks/15.jpg", description: "Floral design: Bloom where you bly.", hasVariants: false },
    { id: "bm16", category: "Bookmarks", name: "Greater Love", basePrice: 25, image: "/Bookmarks/16.jpg", description: "John 15:13 - Greater love has no one than this.", hasVariants: false },
    { id: "bm17", category: "Bookmarks", name: "Faith Hope Love", basePrice: 25, image: "/Bookmarks/17.jpg", description: "1 Corinthians 13:13.", hasVariants: false },
    { id: "bm18", category: "Bookmarks", name: "Stars Worship", basePrice: 25, image: "/Bookmarks/18.jpg", description: "If the stars were made to worship so will I.", hasVariants: false },
    { id: "bm19", category: "Bookmarks", name: "New Mercies", basePrice: 25, image: "/Bookmarks/19.jpg", description: "Mercies are new every morning.", hasVariants: false },
    { id: "bm20", category: "Bookmarks", name: "Done in Love", basePrice: 25, image: "/Bookmarks/20.jpg", description: "1 Corinthians 16:14 - Let all that you do be done in love.", hasVariants: false },
    { id: "bm21", category: "Bookmarks", name: "Mountain Range Watercolor", basePrice: 25, image: "/Bookmarks/21.jpg", description: "Serene watercolor landscape.", hasVariants: false },
    { id: "bm22", category: "Bookmarks", name: "Green Floral Cross", basePrice: 25, image: "/Bookmarks/22.jpg", description: "Cross design entwined with fresh greenery.", hasVariants: false },
    { id: "bm23", category: "Bookmarks", name: "Lost in the Pages", basePrice: 25, image: "/Bookmarks/23.jpg", description: "For the avid reader.", hasVariants: false },
    { id: "bm24", category: "Bookmarks", name: "White Floral Cross", basePrice: 25, image: "/Bookmarks/24.jpg", description: "Elegant cross with white floral accents.", hasVariants: false },
    { id: "bm25", category: "Bookmarks", name: "Walking on Water", basePrice: 25, image: "/Bookmarks/25.jpg", description: "Jesus walking on water illustration.", hasVariants: false },
    { id: "bm26", category: "Bookmarks", name: "Jesus Hugs", basePrice: 25, image: "/Bookmarks/26.jpg", description: "Heartwarming illustration of Jesus hugging a girl.", hasVariants: false },
    { id: "bm27", category: "Bookmarks", name: "Serene Boat", basePrice: 25, image: "/Bookmarks/27.jpg", description: "Peaceful boat on a river scene.", hasVariants: false },
    { id: "bm28", category: "Bookmarks", name: "Sunflowers", basePrice: 25, image: "/Bookmarks/28.jpg", description: "Bright and cheerful sunflower design.", hasVariants: false },
    { id: "bm29", category: "Bookmarks", name: "One Page at a Time", basePrice: 25, image: "/Bookmarks/29.jpg", description: "Reading motivation design.", hasVariants: false },
    { id: "bm30", category: "Bookmarks", name: "Fir Tree", basePrice: 25, image: "/Bookmarks/30.jpg", description: "Minimalist fir tree illustration.", hasVariants: false },
    { id: "bm31", category: "Bookmarks", name: "Sunrise Sketch", basePrice: 25, image: "/Bookmarks/31.jpg", description: "Artistic pencil sketch of a sunrise.", hasVariants: false },
    { id: "bm32", category: "Bookmarks", name: "God's Hand Reaching", basePrice: 25, image: "/Bookmarks/32.jpg", description: "Divine connection illustration.", hasVariants: false },
    { id: "bm33", category: "Bookmarks", name: "Dreams Blossom", basePrice: 25, image: "/Bookmarks/33.jpg", description: "Dreams blossom in silence.", hasVariants: false },
    { id: "bm34", category: "Bookmarks", name: "Breathe Hope Bloom", basePrice: 25, image: "/Bookmarks/34.jpg", description: "Breathe hope, bloom, flourish.", hasVariants: false },
    { id: "bm35", category: "Bookmarks", name: "Do Not Fear", basePrice: 25, image: "/Bookmarks/35.jpg", description: "Do not fear for I am with you.", hasVariants: false, className:"rotate-45" },
    
    // FILE 2: POSTERS (Pages 5-End)
    { id: "po1", category: "Posters", name: "Faith Hope", basePrice: { min: 20, max: 80 } , image: "/Posters/1.jpg", description: "Hebrews 11:1 variant.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po2", category: "Posters", name: "Plans to Prosper", basePrice: { min: 20, max: 80 }, image: "/Posters/2.jpg", description: "Jeremiah 29:11 Poster.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po3", category: "Posters", name: "God So Loved", basePrice: { min: 20, max: 80 }, image: "/Posters/3.jpg", description: "John 3:16 Poster.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po4", category: "Posters", name: "Think Positively", basePrice: { min: 20, max: 80 }, image: "/Posters/4.jpg", description: "List of positive habits.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po5", category: "Posters", name: "Whatever It Takes", basePrice: { min: 20, max: 80 }, image: "/Posters/5.jpg", description: "Motivational bold text.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po6", category: "Posters", name: "Fearfully & Wonderfully Made", basePrice: { min: 20, max: 80 }, image: "/Posters/6.jpg", description: "Psalm 139:14 declaration of self-worth.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po7", category: "Posters", name: "Psalm 91 Full", basePrice: { min: 20, max: 80 }, image: "/Posters/7.jpg", description: "The complete text of the Psalm of protection.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po8", category: "Posters", name: "Saved The World", basePrice: { min: 20, max: 80 }, image: "/Posters/8.jpg", description: "John 3:16-17.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
   // { id: "po9", category: "Posters", name: "Stay Pawsitive", basePrice: { min: 20, max: 80 }, image: "/Posters/9.jpg", description: "Cute animal pun design.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po10", category: "Posters", name: "Hallelujah Definition", basePrice: { min: 20, max: 80 }, image: "/Posters/10.jpg", description: "Dictionary style definition of the Hebrew word.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po11", category: "Posters", name: "While We Were Sinners", basePrice: { min: 20, max: 80 }, image: "/Posters/11.jpg", description: "Romans 5:8 - Christ died for us.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po12", category: "Posters", name: "Forever Kinda Love", basePrice: { min: 20, max: 80 }, image: "/Posters/12.jpg", description: "Matthew 28:20 inspired romantic-style faith design.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po13", category: "Posters", name: "Ave Maria", basePrice: { min: 20, max: 80 }, image: "/Posters/13.jpg", description: "Gentle Marian illustration suitable for prayer corners.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po14", category: "Posters", name: "Saved By Grace", basePrice: { min: 20, max: 80 }, image: "/Posters/14.jpg", description: "Ephesians 2:8.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po15", category: "Posters", name: "Original Love Letters", basePrice: { min: 20, max: 80 }, image: "/Posters/15.jpg", description: "Bible OXOX Design.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po16", category: "Posters", name: "I Am The Way", basePrice: { min: 20, max: 80 }, image: "/Posters/16.jpg", description: "John 14:6 declaration: Way, Truth, and Life.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po17", category: "Posters", name: "Psalm 23", basePrice: { min: 20, max: 80 }, image: "/Posters/17.jpg", description: "The Lord is my shepherd.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po18", category: "Posters", name: "Psalm 91:4", basePrice: { min: 20, max: 80 }, image: "/Posters/18.jpg", description: "Feathers protection poster.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po19", category: "Posters", name: "I'd Rather Have Jesus", basePrice: { min: 20, max: 80 }, image: "/Posters/19.jpg", description: "Devotional poster.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po20", category: "Posters", name: "Blessed", basePrice: { min: 20, max: 80 }, image: "/Posters/20.jpg", description: "Simple Blessed Typography.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po21", category: "Posters", name: "You Are Loved", basePrice: { min: 20, max: 80 }, image: "/Posters/21.jpg", description: "Affirmation poster.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po22", category: "Posters", name: "Holy Holy Holy", basePrice: { min: 20, max: 80 }, image: "/Posters/22.jpg", description: "Worship declaration: Lord God Almighty.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po23", category: "Posters", name: "Trust In The Lord", basePrice: { min: 20, max: 80 }, image: "/Posters/23.jpg", description: "Proverbs 3:5 - With all your heart.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po24", category: "Posters", name: "Chosen Loved Beautiful", basePrice: { min: 20, max: 80 }, image: "/Posters/24.jpg", description: "Affirmation of beauty and worth.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po25", category: "Posters", name: "Daughter of the King – Light", basePrice: { min: 20, max: 80 }, image: "/Posters/25.jpg", description: "Alternate illustration celebrating representation.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po26", category: "Posters", name: "The Boss Jesus", basePrice: { min: 20, max: 80 }, image: "/Posters/26.jpg", description: "Bold poster portraying Jesus as authority and leader.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    //{ id: "po27", category: "Posters", name: "Created with Purpose", basePrice: { min: 20, max: 80 }, image: "/Posters/27.jpg", description: "Affirmation of divine purpose.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po28", category: "Posters", name: "Watercolor Cross", basePrice: { min: 20, max: 80 }, image: "/Posters/28.jpg", description: "Artistic watercolor cross design.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po29", category: "Posters", name: "The 100th Sheep", basePrice: { min: 20, max: 80 }, image: "/Posters/29.jpg", description: "Wanted: The lost sheep found by the Shepherd.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po30", category: "Posters", name: "Jesus Minimal Art", basePrice: { min: 20, max: 80 }, image: "/Posters/30.jpg", description: "Modern minimalist digital art of Jesus.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po31", category: "Posters", name: "Good Shepherd & Sheep", basePrice: { min: 20, max: 80 }, image: "/Posters/31.jpg", description: "Classic illustration of the Shepherd caring for His flock.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po32", category: "Posters", name: "Walking on Water", basePrice: { min: 20, max: 80 }, image: "/Posters/32.jpg", description: "Miracle of Jesus walking on water.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po33", category: "Posters", name: "Jesus Hugs", basePrice: { min: 20, max: 80 }, image: "/Posters/33.jpg", description: "Heartwarming illustration of Jesus hugging a girl.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po34", category: "Posters", name: "Floral Cross", basePrice: { min: 20, max: 80 }, image: "/Posters/34.jpg", description: "Cross adorned with beautiful flowers.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po35", category: "Posters", name: "Purple Heart", basePrice: { min: 20, max: 80 }, image: "/Posters/35.jpg", description: "Spiritual heart design in purple.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po36", category: "Posters", name: "The Good Shepherd", basePrice: { min: 20, max: 80 }, image: "/Posters/36.jpg", description: "Portrait of Jesus as the Good Shepherd.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },
    { id: "po37", category: "Posters", name: "Daughter of the King II", basePrice: { min: 20, max: 80 }, image: "/Posters/37.jpg", description: "Alternative design celebrating royal identity.", hasVariants: true, variants: [{ name: "Size", options: ["A5", "A4", "A3"] }] },

    // --- DIARIES ---
    { id: "di1", category: "Diaries", name: "Watercolor Cross Diary", basePrice: 249, image: "/Diaries/1.jpg", description: "A soft watercolor cross design symbolising sacrifice, grace, and quiet reflection. Ideal for prayer journaling and personal notes.", hasVariants: false },
    { id: "di2", category: "Diaries", name: "Trust in the Lord Diary", basePrice: 249, image: "/Diaries/2.jpg", description: "Inspired by Proverbs, this diary encourages surrender, faith, and wholehearted trust in God.", hasVariants: false },
    { id: "di3", category: "Diaries", name: "For I Know the Plans", basePrice: 249, image: "/Diaries/3.jpg", description: "A Jeremiah 29:11 inspired design. Created for purpose-filled journaling.", hasVariants: false },
    { id: "di4", category: "Diaries", name: "The Boss – Jesus (The Chosen)", basePrice: 249, image: "/Diaries/4.jpg", description: "Bold diary design portraying Jesus as authority and leader, inspired by The Chosen series.", hasVariants: false },
    { id: "di5", category: "Diaries", name: "Chosen, Loved, Beautiful Diary", basePrice: 249, image: "/Diaries/5.jpg", description: "Affirmation-based diary celebrating identity, worth, and belonging in Christ.", hasVariants: false },
    { id: "di6", category: "Diaries", name: "Daughter of the King – Light Skin Diary", basePrice: 249, image: "/Diaries/6.jpg", description: "An identity-affirming diary reminding you of your royal worth and calling in Christ.", hasVariants: false },
    { id: "di7", category: "Diaries", name: "Daughter of the King – Dark Skin Diary", basePrice: 249, image: "/Diaries/7.jpg", description: "A representation-focused design celebrating dignity, identity, and faith.", hasVariants: false },
    { id: "di8", category: "Diaries", name: "Psalm 91 – Under His Wings Diary", basePrice: 249, image: "/Diaries/8.jpg", description: "Psalm 91:4 inspired diary highlighting refuge, protection, and God’s covering wings.", hasVariants: false },
    { id: "di9", category: "Diaries", name: "Yeshua – Lion of Judah", basePrice: 249, image: "/Diaries/9.jpg", description: "Powerful artwork of Yeshua as the Lion of Judah, symbolising authority, victory, and kingship.", hasVariants: false },
    { id: "di10", category: "Diaries", name: "With God All Things Are Possible", basePrice: 249, image: "/Diaries/10.jpg", description: "Faith-forward typography diary inspired by Matthew 19:26, created to fuel hope and perseverance.", hasVariants: false },
    { id: "di11", category: "Diaries", name: "Just a Girl Who Loves Jesus", basePrice: 249, image: "/Diaries/11.jpg", description: "Soft, modern diary design celebrating simple, everyday love for Jesus.", hasVariants: false },
    { id: "di12", category: "Diaries", name: "Saved by Grace Diary", basePrice: 249, image: "/Diaries/12.jpg", description: "Minimal typography diary celebrating salvation through grace alone.", hasVariants: false },
    { id: "di13", category: "Diaries", name: "Let All That You Do Be Done in Love", basePrice: 249, image: "/Diaries/13.jpg", description: "Scripture-inspired diary encouraging love as the foundation of all actions and decisions.", hasVariants: false },
  
];

// Helper functions (Optional use, but good to have)
export async function getProducts() {
    return PRODUCTS;
}

export async function getProductById(id) {
    return PRODUCTS.find(p => p.id === id);
}